require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'toktok' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Pods for toktok
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Firebase/Core'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'RNQrGenerator', :path => '../node_modules/rn-qr-generator'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  # For React Native Permissions on iOS
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"

  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
  'FaceDetectorMLKit'
  ]

  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'react-native-location', :path => '../node_modules/react-native-location'

  target 'toktokTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # you should disable the next line.
  use_flipper!()

  # Comment the code below if not running M1 macs.
  # post_install do |installer|
  #   react_native_post_install(installer)
  #   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  # end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal', '>= 3.0', '< 4.0'
end


